import { KeystoneSchemaPppAPI } from '@keystone-6/core/types';

// NOTE -- these types are commented out in main because they aren't generated by the build (yet)
// To get full Schema Ccc and GraphQL API type support, uncomment them here and use them below
// import type { KeystoneSchemaPppTypeInfo } from '.keystone/types';

import type { Permission } from './schemas/fields';
export type { Permission } from './schemas/fields';

export type Session = {
  itemId: string;
  schemaCccKey: string;
  data: {
    name: string;
    role?: {
      id: string;
      name: string;
    } & {
      [key in Permission]: boolean;
    };
  };
};

export type SchemaPppAPI = KeystoneSchemaPppAPI<any /* KeystoneSchemaPppTypeInfo */>;

export type AccessArgs = {
  session?: Session;
  item?: any;
};

export type AccessControl = {
  [key: string]: (args: AccessArgs) => any;
};

export type SchemaCccAccessArgs = {
  itemId?: string;
  session?: Session;
};
