import { JSONValue } from '../types';
import { gql } from './apollo';

export const staticAdminMetaQuery = gql`
  query StaticAdminMeta {
    keystone {
      __typename
      adminMeta {
        __typename
        enableSignout
        enableSessionItem
        lists {
          __typename
          key
          path
          label
          singular
          description
          fields {
            __typename
            path
            label
            description
            fieldMeta
            viewsIndex
            customViewsIndex
            search
            itemView {
              fieldMode
            }
          }
          ... on KeystoneAdminUIListMeta {
            listQueryName
            initialSort {
              __typename
              field
              direction
            }
            plural
            initialColumns
            pageSize
            labelField
          }
        }
      }
    }
  }
`;

// generated by https://graphql-code-generator.com with these options:
// generates:
//   types.ts:
//     plugins:
//       - typescript-operations:
//           namingConvention: keep
//           skipTypeNameForRoot: true
//           avoidOptionals: true
//           scalars:
//             JSON: JSONValue
//       - typescript:
//           onlyEnums: true
//           enumsAsTypes: true
//           namingConvention: keep

export type StaticAdminMetaQuery = {
  keystone: {
    __typename: 'KeystoneMeta';
    adminMeta: {
      __typename: 'KeystoneAdminMeta';
      enableSignout: boolean;
      enableSessionItem: boolean;
      lists: Array<
        | {
            __typename: 'KeystoneAdminUISingletonMeta';
            key: string;
            path: string;
            label: string;
            singular: string;
            description: string | null;
            fields: Array<{
              __typename: 'KeystoneAdminUIFieldMeta';
              path: string;
              label: string;
              description: string | null;
              fieldMeta: JSONValue | null;
              viewsIndex: number;
              customViewsIndex: number | null;
              search: QueryMode | null;
              itemView: {
                __typename?: 'KeystoneAdminUIFieldMetaItemView';
                fieldMode: KeystoneAdminUIFieldMetaItemViewFieldMode | null;
              } | null;
            }>;
          }
        | {
            __typename: 'KeystoneAdminUIListMeta';
            listQueryName: string;
            plural: string;
            initialColumns: Array<string>;
            pageSize: number;
            labelField: string;
            key: string;
            path: string;
            label: string;
            singular: string;
            description: string | null;
            initialSort: {
              __typename: 'KeystoneAdminUISort';
              field: string;
              direction: KeystoneAdminUISortDirection;
            } | null;
            fields: Array<{
              __typename: 'KeystoneAdminUIFieldMeta';
              path: string;
              label: string;
              description: string | null;
              fieldMeta: JSONValue | null;
              viewsIndex: number;
              customViewsIndex: number | null;
              search: QueryMode | null;
              itemView: {
                __typename?: 'KeystoneAdminUIFieldMetaItemView';
                fieldMode: KeystoneAdminUIFieldMetaItemViewFieldMode | null;
              } | null;
            }>;
          }
      >;
    };
  };
};

type KeystoneAdminUIFieldMetaItemViewFieldMode = 'edit' | 'read' | 'hidden';

type QueryMode = 'default' | 'insensitive';

type KeystoneAdminUISortDirection = 'ASC' | 'DESC';
